global using AvaloniaEdit.Document;
global using AvaloniaEdit.Folding;
global using ICSharpCode.ILSpy.Docking;
global using ICSharpCode.ILSpy.Util;

global using System.Windows;

global using App = ProjectRover.App;
global using BackgroundGeometryBuilder = AvaloniaEdit.Rendering.BackgroundGeometryBuilder;
global using Binding = Avalonia.Data.Binding;
global using Brush = Avalonia.Media.Brush;
global using Button = Avalonia.Controls.Button;
global using CanExecuteRoutedEventArgs = Avalonia.Labs.Input.CanExecuteRoutedEventArgs;
global using CheckBox = Avalonia.Controls.CheckBox;
global using GroupBox = ProjectRover.Controls.GroupBox;
global using Color = Avalonia.Media.Color;
global using Colors = Avalonia.Media.Colors;
global using CommandBinding = Avalonia.Labs.Input.CommandBinding;
global using CommandManager = Avalonia.Labs.Input.CommandManager;
global using DocumentHighlighter = AvaloniaEdit.Highlighting.DocumentHighlighter;
global using DrawingContext = Avalonia.Media.DrawingContext;
global using ExecutedRoutedEventArgs = Avalonia.Labs.Input.ExecutedRoutedEventArgs;
global using FontWeight = Avalonia.Media.FontWeight;
global using FrameworkElement = Avalonia.Controls.Control;
global using Geometry = Avalonia.Media.Geometry;
global using HighlightingColor = AvaloniaEdit.Highlighting.HighlightingColor;
global using HighlightingColorizer = AvaloniaEdit.Highlighting.HighlightingColorizer;
global using HighlightingManager = AvaloniaEdit.Highlighting.HighlightingManager;
global using HorizontalAlignment = Avalonia.Layout.HorizontalAlignment;
global using IBackgroundRenderer = AvaloniaEdit.Rendering.IBackgroundRenderer;
global using IDocument = AvaloniaEdit.Document.IDocument;
global using IHighlightingDefinition = AvaloniaEdit.Highlighting.IHighlightingDefinition;
global using Image = Avalonia.Controls.Image;
global using ImageSource = System.Object;
global using InlineObjectElement = AvaloniaEdit.Rendering.InlineObjectElement;
global using IValueConverter = Avalonia.Data.Converters.IValueConverter;
global using IVisualLineTransformer = AvaloniaEdit.Rendering.IVisualLineTransformer;
global using Key = Avalonia.Input.Key;
global using KeyGesture = Avalonia.Input.KeyGesture;
global using KnownLayer = AvaloniaEdit.Rendering.KnownLayer;
global using LinkElementGenerator = AvaloniaEdit.Rendering.LinkElementGenerator;
global using ModifierKeys = Avalonia.Input.KeyModifiers;
global using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
global using OpenFolderDialog = Microsoft.Win32.OpenFolderDialog;
global using Orientation = Avalonia.Layout.Orientation;
global using Pen = Avalonia.Media.Pen;
global using Rect = Avalonia.Rect;
global using RelativeSourceMode = Avalonia.Data.RelativeSourceMode;
global using RichText = AvaloniaEdit.Highlighting.RichText;
global using RichTextModel = AvaloniaEdit.Highlighting.RichTextModel;
global using RoutedEventArgs = Avalonia.Interactivity.RoutedEventArgs;
global using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
global using SimpleHighlightingBrush = AvaloniaEdit.Highlighting.SimpleHighlightingBrush;
global using SolidColorBrush = Avalonia.Media.SolidColorBrush;
global using StackPanel = Avalonia.Controls.StackPanel;
global using TextBlock = Avalonia.Controls.TextBlock;
global using TextEditor = AvaloniaEdit.TextEditor;
global using TextViewPosition = AvaloniaEdit.TextViewPosition;
global using Thickness = Avalonia.Thickness;
global using ToggleButton = Avalonia.Controls.Primitives.ToggleButton;
global using UIElement = Avalonia.Controls.Control;
global using VerticalAlignment = Avalonia.Layout.VerticalAlignment;
global using VisualLine = AvaloniaEdit.Rendering.VisualLine;
global using VisualLineElement = AvaloniaEdit.Rendering.VisualLineElement;
global using VisualLineElementGenerator = AvaloniaEdit.Rendering.VisualLineElementGenerator;
global using VisualLineText = AvaloniaEdit.Rendering.VisualLineText;
global using Window = Avalonia.Controls.Window;
global using WindowState = Avalonia.Controls.WindowState;

global using static Avalonia.Controls.ResourceNodeExtensions;

global using PaneModel = Dock.Model.TomsToolbox.Core.DockableBase;
global using FileReader = AvaloniaEdit.Utils.FileReader;
global using DataGrid = Avalonia.Controls.DataGrid;
global using DataTemplate = Avalonia.Markup.Xaml.Templates.DataTemplate;
global using DependencyObject = Avalonia.AvaloniaObject;
global using DataGridTextColumn = Avalonia.Controls.DataGridTextColumn;
global using ScrollViewer = Avalonia.Controls.ScrollViewer;
global using DataGridRowDetailsVisibilityMode = Avalonia.Controls.DataGridRowDetailsVisibilityMode;
global using Visibility = Avalonia.Controls.DataGridRowDetailsVisibilityMode;
global using DataGridAutoGeneratingColumnEventArgs = Avalonia.Controls.DataGridAutoGeneratingColumnEventArgs;
global using DataGridColumn = Avalonia.Controls.DataGridColumn;
global using DataGridCheckBoxColumn = Avalonia.Controls.DataGridCheckBoxColumn;
global using DataGridTemplateColumn = Avalonia.Controls.DataGridTemplateColumn;
global using DataGridGridLinesVisibility = Avalonia.Controls.DataGridGridLinesVisibility;
global using DataGridHeadersVisibility = Avalonia.Controls.DataGridHeadersVisibility;
global using DataGridSelectionMode = Avalonia.Controls.DataGridSelectionMode;
global using DataGridSelectionUnit = Avalonia.Controls.DataGridSelectionUnit;
global using BindingMode = Avalonia.Data.BindingMode;
global using ControlTemplate = Avalonia.Markup.Xaml.Templates.ControlTemplate;
global using Style = Avalonia.Styling.Style;
global using Run = Avalonia.Controls.Documents.Run;
global using Bold = Avalonia.Controls.Documents.Bold;
global using LineBreak = Avalonia.Controls.Documents.LineBreak;
