global using System.Windows;

global using ICSharpCode.ILSpy.Commands;
global using ICSharpCode.ILSpy.Util;
global using ICSharpCode.ILSpy.Docking;

global using Avalonia.Labs.Input;
global using Avalonia.Controls;
global using Avalonia.Data;
global using ImageSource = System.Object;
global using IHighlightingDefinition = AvaloniaEdit.Highlighting.IHighlightingDefinition;
global using HighlightingColor = AvaloniaEdit.Highlighting.HighlightingColor;
global using HighlightingManager = AvaloniaEdit.Highlighting.HighlightingManager;
global using Window = Avalonia.Controls.Window;
global using RoutedEventArgs = Avalonia.Interactivity.RoutedEventArgs;
global using Key = Avalonia.Input.Key;
global using ModifierKeys = Avalonia.Input.KeyModifiers;
global using App = ProjectRover.App;
global using WindowState = Avalonia.Controls.WindowState;
global using Colors = Avalonia.Media.Colors;
global using Color = Avalonia.Media.Color;
global using KeyGesture = Avalonia.Input.KeyGesture;
global using FontWeight = Avalonia.Media.FontWeight;
global using SimpleHighlightingBrush = AvaloniaEdit.Highlighting.SimpleHighlightingBrush;
global using RichText = AvaloniaEdit.Highlighting.RichText;
global using OpenFolderDialog = Microsoft.Win32.OpenFolderDialog;
global using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
global using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
global using Thickness = Avalonia.Thickness;
global using Orientation = Avalonia.Layout.Orientation;
global using RichTextModel = AvaloniaEdit.Highlighting.RichTextModel;
global using DocumentHighlighter = AvaloniaEdit.Highlighting.DocumentHighlighter;
global using HighlightingColorizer = AvaloniaEdit.Highlighting.HighlightingColorizer;
global using VisualLineElementGenerator = AvaloniaEdit.Rendering.VisualLineElementGenerator;
global using VisualLineElement = AvaloniaEdit.Rendering.VisualLineElement;
global using InlineObjectElement = AvaloniaEdit.Rendering.InlineObjectElement;
global using VisualLine = AvaloniaEdit.Rendering.VisualLine;
global using VisualLineText = AvaloniaEdit.Rendering.VisualLineText;
global using AvaloniaEdit.Document;
global using AvaloniaEdit.Folding;
global using TextViewPosition = AvaloniaEdit.TextViewPosition;
global using SolidColorBrush = Avalonia.Media.SolidColorBrush;
global using AvaloniaEdit.Rendering;
global using TextEditor = AvaloniaEdit.TextEditor;
global using IBackgroundRenderer = AvaloniaEdit.Rendering.IBackgroundRenderer;
global using IVisualLineTransformer = AvaloniaEdit.Rendering.IVisualLineTransformer;
global using IDocument = AvaloniaEdit.Document.IDocument;
global using UIElement = Avalonia.Controls.Control;
global using FrameworkElement = Avalonia.Controls.Control;
global using Rect = Avalonia.Rect;
global using TextArea = AvaloniaEdit.Editing.TextArea;
global using Pen = Avalonia.Media.Pen;
global using Adorner = Avalonia.Controls.Primitives.AdornerLayer;
global using DrawingContext = Avalonia.Media.DrawingContext;
global using RectangleGeometry = Avalonia.Media.RectangleGeometry;
global using Geometry = Avalonia.Media.Geometry;
global using Brush = Avalonia.Media.Brush;
global using IValueConverter = Avalonia.Data.Converters.IValueConverter;
global using FontFamily = Avalonia.Media.FontFamily;
global using HorizontalAlignment = Avalonia.Layout.HorizontalAlignment;
global using VerticalAlignment = Avalonia.Layout.VerticalAlignment;
global using ToggleButton = Avalonia.Controls.Primitives.ToggleButton;