using System;
using System.Collections.ObjectModel;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;
using Dock.Avalonia.Controls;
using Dock.Model.Avalonia;
using ICSharpCode.ILSpy.Search;
using ICSharpCode.ILSpy.AssemblyTree;
using System.Windows.Threading;
using Avalonia.Controls.Templates;
using Avalonia.Controls.Presenters;
using ICSharpCode.ILSpy.ViewModels;
using Dock.Model.TomsToolbox.Controls;
using Dock.Model.Core;
using System.Reflection;

namespace ICSharpCode.ILSpy
{
    public partial class MainWindow : Window
    {
        private MainWindowViewModel? viewModel;

        public MainWindow()
        {
            InitializeComponent();
            var dockHost = this.FindControl<DockControl>("DockHost");
            var documentTemplate = new FuncDataTemplate<TabPageModel>(
                (data, scope) => {
                    var contentPresenter = new ContentPresenter { DataContext = data };
                    contentPresenter.Bind(ContentPresenter.ContentProperty, new Binding("Content"));
                    return contentPresenter;
                }
            );
            dockHost.DataTemplates.Add(documentTemplate);
            var toolTemplate = new FuncDataTemplate<Tool>(
                (data, scope) => new ContentPresenter { DataContext = data, Content = data.Content }
            );
            dockHost.DataTemplates.Add(toolTemplate);
#if DEBUG
            this.AttachDevTools();
            Console.WriteLine("[Log][MainWindow] DevTools attached.");
#endif

            // Set the window title to include ProjectRover version (short: major.minor)
            try {
                var ver = GetRoverShortVersion();
                if (!string.IsNullOrEmpty(ver))
                    this.Title = this.Title + " (v" + ver + ")";
            } catch { }
			Dispatcher.CurrentDispatcher.BeginInvoke(DispatcherPriority.Background, () => {
				viewModel.Workspace.InitializeLayout();
				MessageBus.Send(this, new MainWindowLoadedEventArgs());
			});
        }


        private static string? GetRoverShortVersion()
        {
            // 1. Try GitVersionInformation (generated by GitVersion.MsBuild)
            var asm = Assembly.GetExecutingAssembly();
            var gvType = asm.GetType("GitVersionInformation");
            if (gvType != null)
            {
                // Prefer Major + Minor fields if present
                var major = gvType.GetField("Major", BindingFlags.Static | BindingFlags.Public)?.GetValue(null) as string;
                var minor = gvType.GetField("Minor", BindingFlags.Static | BindingFlags.Public)?.GetValue(null) as string;
                if (!string.IsNullOrWhiteSpace(major) && !string.IsNullOrWhiteSpace(minor))
                    return $"{major}.{minor}";
            }

            return null;
        }

        public MainWindow(MainWindowViewModel viewModel) : this()
        {
            this.viewModel = viewModel;
            DataContext = viewModel;
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }

    }
}
