/*
    Copyright 2024 CodeMerx
    Copyright 2025-2026 LeXtudio Inc.
    This file is part of ProjectRover.

    ProjectRover is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    ProjectRover is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with ProjectRover.  If not, see<https://www.gnu.org/licenses/>.
*/

using System;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;
using Dock.Avalonia.Controls;
using System.Windows.Threading;
using System.Reflection;
using ICSharpCode.ILSpy.Views;
using ICSharpCode.ILSpy.ViewModels;

namespace ICSharpCode.ILSpy
{
    public partial class MainWindow : Window
    {
        private readonly Serilog.ILogger log = ICSharpCode.ILSpy.Util.LogCategory.For("Session");
        private MainWindowViewModel? viewModel;

        public MainWindow()
        {
            InitializeComponent();
            var dockHost = this.FindControl<DockControl>("DockHost");
            var updatePanelControl = this.FindControl<UpdatePanel>("UpdatePanel");
            if (updatePanelControl != null)
            {
                var updatePanelViewModel = ProjectRover.App.ExportProvider?.GetExportedValueOrDefault<UpdatePanelViewModel>();
                if (updatePanelViewModel != null)
                {
                    updatePanelControl.DataContext = updatePanelViewModel;
                }
            }
#if DEBUG
            this.AttachDevTools();
            log.Debug("DevTools attached.");
#endif

            // Set the window title to include ProjectRover version (major.minor)
            var ver = GetRoverShortVersion();
            if (!string.IsNullOrEmpty(ver))
                this.Title = $"{this.Title} (v{ver})";
			Dispatcher.CurrentDispatcher.BeginInvoke(DispatcherPriority.Background, () => {
				viewModel.Workspace.InitializeLayout();
				MessageBus.Send(this, new MainWindowLoadedEventArgs());
			});
        }

        public static string? GetRoverShortVersion()
        {
            // 1. Try GitVersionInformation (generated by GitVersion.MsBuild)
            var asm = Assembly.GetExecutingAssembly();
            var gvType = asm.GetType("GitVersionInformation");
            if (gvType != null)
            {
                // Prefer Major + Minor fields if present
                var major = gvType.GetField("Major", BindingFlags.Static | BindingFlags.Public)?.GetValue(null) as string;
                var minor = gvType.GetField("Minor", BindingFlags.Static | BindingFlags.Public)?.GetValue(null) as string;
                var patch = gvType.GetField("Patch", BindingFlags.Static | BindingFlags.Public)?.GetValue(null) as string;
                if (!string.IsNullOrWhiteSpace(major) && !string.IsNullOrWhiteSpace(minor))
                    return $"{major}.{minor}.{patch}";
            }

            var informationalVersion = asm.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;
            if (ICSharpCode.ILSpy.Updates.AppUpdateService.TryParseVersionString(informationalVersion, out var infoVersion))
                return $"{infoVersion.Major}.{infoVersion.Minor}.{infoVersion.Build}";

            return null;
        }

        public MainWindow(MainWindowViewModel viewModel) : this()
        {
            this.viewModel = viewModel;
            DataContext = viewModel;
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }

        protected override void OnClosing(WindowClosingEventArgs e)
        {
            try
            {
                var exportProvider = ProjectRover.App.ExportProvider;
                if (exportProvider != null)
                {
                    var settingsService = exportProvider.GetExportedValue<ICSharpCode.ILSpy.Util.SettingsService>();
                    if (settingsService != null)
                    {
                        var snapshot = settingsService.CreateSnapshot();
                        var sessionSettings = snapshot.GetSettings<ICSharpCode.ILSpy.SessionSettings>();

                        // Map Avalonia window bounds/state into SessionSettings so window position persists like WPF
                        try
                        {
                            // Avalonia.Bounds is a Rect with position and size
                            var b = this.Bounds;
                            sessionSettings.WindowBounds = new System.Windows.Rect(b.X, b.Y, b.Width, b.Height);

                            // Map Avalonia WindowState to System.Windows.WindowState
                            switch (this.WindowState)
                            {
                                case WindowState.Maximized:
                                    sessionSettings.WindowState = System.Windows.WindowState.Maximized;
                                    break;
                                case WindowState.Minimized:
                                    sessionSettings.WindowState = System.Windows.WindowState.Minimized;
                                    break;
                                default:
                                    sessionSettings.WindowState = System.Windows.WindowState.Normal;
                                    break;
                            }
                        }
                        catch (Exception ex)
                        {
                                log.Error(ex, "Failed mapping window bounds/state");
                        }

                        // Let interested components write their session state (e.g. selected tree node)
                        ICSharpCode.ILSpy.Util.MessageBus.Send(this, new ICSharpCode.ILSpy.Util.ApplySessionSettingsEventArgs(sessionSettings));

                        try
                        {
                            // Ensure layout is saved into Rover settings before snapshot is persisted.
                            viewModel?.Workspace.SaveLayout();
                            snapshot.Save();
                        }
                        catch (Exception ex)
                        {
                            log.Error(ex, "Failed saving session settings on close");
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                log.Error(ex, "Failed applying session settings on close");
            }

            base.OnClosing(e);
        }

    }
}
