using System;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;
using Dock.Avalonia.Controls;
using System.Windows.Threading;
using System.Reflection;

namespace ICSharpCode.ILSpy
{
    public partial class MainWindow : Window
    {
        private MainWindowViewModel? viewModel;

        public MainWindow()
        {
            InitializeComponent();
            var dockHost = this.FindControl<DockControl>("DockHost");
#if DEBUG
            this.AttachDevTools();
            Console.WriteLine("[Log][MainWindow] DevTools attached.");
#endif

            // Set the window title to include ProjectRover version (major.minor)
            var ver = GetRoverShortVersion();
            if (!string.IsNullOrEmpty(ver))
                this.Title = $"{this.Title} (v{ver})";
			Dispatcher.CurrentDispatcher.BeginInvoke(DispatcherPriority.Background, () => {
				viewModel.Workspace.InitializeLayout();
				MessageBus.Send(this, new MainWindowLoadedEventArgs());
			});
        }

        public static string? GetRoverShortVersion()
        {
            // 1. Try GitVersionInformation (generated by GitVersion.MsBuild)
            var asm = Assembly.GetExecutingAssembly();
            var gvType = asm.GetType("GitVersionInformation");
            if (gvType != null)
            {
                // Prefer Major + Minor fields if present
                var major = gvType.GetField("Major", BindingFlags.Static | BindingFlags.Public)?.GetValue(null) as string;
                var minor = gvType.GetField("Minor", BindingFlags.Static | BindingFlags.Public)?.GetValue(null) as string;
                var patch = gvType.GetField("Patch", BindingFlags.Static | BindingFlags.Public)?.GetValue(null) as string;
                if (!string.IsNullOrWhiteSpace(major) && !string.IsNullOrWhiteSpace(minor))
                    return $"{major}.{minor}.{patch}";
            }

            var informationalVersion = asm.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;
            if (ICSharpCode.ILSpy.Updates.AppUpdateService.TryParseVersionString(informationalVersion, out var infoVersion))
                return $"{infoVersion.Major}.{infoVersion.Minor}.{infoVersion.Build}";

            return null;
        }

        public MainWindow(MainWindowViewModel viewModel) : this()
        {
            this.viewModel = viewModel;
            DataContext = viewModel;
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }

        protected override void OnClosing(WindowClosingEventArgs e)
        {
            try
            {
                var exportProvider = ProjectRover.App.ExportProvider;
                if (exportProvider != null)
                {
                    var settingsService = exportProvider.GetExportedValue<ICSharpCode.ILSpy.Util.SettingsService>();
                    if (settingsService != null)
                    {
                        var snapshot = settingsService.CreateSnapshot();
                        var sessionSettings = snapshot.GetSettings<ICSharpCode.ILSpy.SessionSettings>();

                        // Let interested components write their session state (e.g. selected tree node)
                        ICSharpCode.ILSpy.Util.MessageBus.Send(this, new ICSharpCode.ILSpy.Util.ApplySessionSettingsEventArgs(sessionSettings));

                        try
                        {
                            snapshot.Save();
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine($"Failed saving session settings on close: {ex}");
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Failed applying session settings on close: {ex}");
            }

            viewModel?.Workspace.SaveLayout();
            base.OnClosing(e);
        }

    }
}
