using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Data.Converters;
using Avalonia.Markup.Xaml;

namespace ICSharpCode.ILSpy.Metadata
{
    public partial class FlagsTooltip : UserControl, IEnumerable<FlagGroup>
    {
        public FlagsTooltip()
        {
            InitializeComponent();
        }

        public void PopulateFromType(Type flagsType, int selectedValue = 0, string header = null)
        {
            if (flagsType == null)
                return;
            var group = FlagGroup.CreateMultipleChoiceGroup(flagsType, header, -1, selectedValue, includeAll: false);
            this.Groups.Clear();
            this.Groups.Add(group);
            ItemsRoot.ItemsSource = Groups;
        }

        public int GetSelectedValue()
        {
            int v = 0;
            foreach (var g in Groups.OfType<MultipleChoiceGroup>())
            {
                foreach (var f in g.Flags)
                {
                    if (f.IsSelected)
                        v |= f.Value;
                }
            }
            return v;
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
            this.DataContext = this;
        }

        public void Add(FlagGroup group)
        {
            Groups.Add(group);
            ItemsRoot.ItemsSource = Groups;
        }

        public IEnumerator<FlagGroup> GetEnumerator() => Groups.GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => Groups.GetEnumerator();

        public List<FlagGroup> Groups { get; } = new List<FlagGroup>();

        // `ItemsRoot` is generated by the Avalonia XAML source generator.
    }

    public class Flag
    {
        public string Name { get; set; }
        public int Value { get; set; }
        public bool IsSelected { get; set; }

        public Flag(string name, int value, bool isSelected)
        {
            this.Name = name;
            this.Value = value;
            this.IsSelected = isSelected;
        }
    }

    public abstract class FlagGroup
    {
        public static MultipleChoiceGroup CreateMultipleChoiceGroup(Type flagsType, string header = null, int mask = -1, int selectedValue = 0, bool includeAll = true)
        {
            MultipleChoiceGroup group = new MultipleChoiceGroup(GetFlags(flagsType, mask, selectedValue, includeAll ? "<All>" : null));
            group.Header = header;
            group.SelectedFlags = selectedValue;
            return group;
        }

        public static SingleChoiceGroup CreateSingleChoiceGroup(Type flagsType, string header = null, int mask = -1, int selectedValue = 0, Flag defaultFlag = default, bool includeAny = true)
        {
            var group = new SingleChoiceGroup(GetFlags(flagsType, mask, selectedValue, includeAny ? "<Any>" : null));
            group.Header = header;
            group.SelectedFlag = group.Flags.SingleOrDefault(f => f.Value == selectedValue);
            if (group.SelectedFlag.Name == null)
            {
                group.SelectedFlag = defaultFlag;
            }
            return group;
        }

        public static IEnumerable<Flag> GetFlags(Type flagsType, int mask = -1, int selectedValues = 0, string neutralItem = null)
        {
            if (neutralItem != null)
                yield return new Flag(neutralItem, -1, false);

            foreach (var item in flagsType.GetFields(BindingFlags.Static | BindingFlags.Public))
            {
                if (item.Name.EndsWith("Mask", StringComparison.Ordinal))
                    continue;
                int value = (int)Convert.ChangeType(item.GetRawConstantValue(), typeof(int));
                if ((value & mask) == 0)
                    continue;
                yield return new Flag($"{item.Name} ({value:X4})", value, (selectedValues & value) != 0);
            }
        }

        public string Header { get; set; }
        public IList<Flag> Flags { get; protected set; }
    }

    public class MultipleChoiceGroup : FlagGroup
    {
        public MultipleChoiceGroup(IEnumerable<Flag> flags)
        {
            this.Flags = flags.ToList();
        }

        public int SelectedFlags { get; set; }
    }

    public class SingleChoiceGroup : FlagGroup
    {
        public SingleChoiceGroup(IEnumerable<Flag> flags)
        {
            this.Flags = flags.ToList();
        }

        public Flag SelectedFlag { get; set; }
    }

    public class NullVisibilityConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            return value != null;
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
}
